services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VUE_APP_API_URL: "http://localhost:8000"
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.prod.env
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./backend/.prod.env
    environment:
      - PGDATA=/var/lib/postgresql/data/db-files/
    ports:
      - "5432:5432"
