# Generated by Django 5.0.1 on 2024-01-23 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_searchedoffer_spottedoffer_delete_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='spottedoffer',
            name='searched_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.searchedoffer'),
            preserve_default=False,
        ),
    ]
