# Generated by Django 5.0.1 on 2024-02-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_spottedoffer_searched_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchedoffer',
            old_name='mileage',
            new_name='mileage_limit',
        ),
        migrations.RenameField(
            model_name='searchedoffer',
            old_name='price',
            new_name='price_limit',
        ),
        migrations.RenameField(
            model_name='searchedoffer',
            old_name='production_year',
            new_name='production_year_from',
        ),
        migrations.AddField(
            model_name='searchedoffer',
            name='production_year_to',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spottedoffer',
            name='img',
            field=models.CharField(default='img'),
            preserve_default=False,
        ),
    ]
